apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: ___________
spec:
  template:
    metadata:
      labels:
        app: ___________
        service: ___________
    spec:
      containers:
        - name: ___________
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ___________
          ports:
            - containerPort: 3306
              name: ___________
