apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
  labels:
    app: ___________
spec:
  rules:
    - host: ___________
      http:
        paths:
          - path: /
            backend:
              serviceName: ___________
              servicePort: ___________
