apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1-depployment
  labels:
    app: nginx-ingress-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ingress-demo
  template:
    metadata:
      labels:
        app: nginx-ingress-demo
    spec:
      containers:
        - name: ct-go-server
          image: wukongsun/nginx-ingress-demo-svc1:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc1-cluster-ip
spec:
  selector:
    app: nginx-ingress-demo
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8888

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: svc1-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: svc1.xxx.com
      http:
        paths:
          - backend:
              serviceName: svc1-cluster-ip
              servicePort: 8888
